Allow only dev to PR compare with master

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -7,6 +7,15 @@ on:
     branches: ['master']
 
 jobs:
+  check_branch: # Allow only dev to PR compare with master
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check branch
+      if: github.base_ref == 'master' && github.head_ref != 'dev'
+      run: |
+        echo "ERROR: You can only merge to main from dev."
+        exit 1
+
   build:
     runs-on: ubuntu-latest
 
